repos:
- hooks:
  - args:
    - --in-place
    - --remove-all-unused-imports
    - --ignore-init-module-imports
    entry: autoflake
    id: autoflake
    language: python
    name: autoflake
    require_serial: true
    types:
    - python
  repo: https://github.com/myint/autoflake
  rev: v2.3.1
- hooks:
  - args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --use-parentheses
    - --line-width=88
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
- hooks:
  - args:
    - --max-line-length=89
    - --max-complexity=15
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 7.0.0
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 24.3.0
- hooks:
  - additional_dependencies:
    - types-toml
    - types-setuptools
    - types-requests
    - types-attrs
    args:
    - --ignore-missing-imports
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
- hooks:
  - args:
    - --convention=google
    - --add-ignore=D104
    id: pydocstyle
  repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
- hooks:
  - files: ^docs/.*\.mdx?$
    id: prettier
  repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
- hooks:
  - exclude: ^docs/*
    id: trailing-whitespace
  - exclude: ^docs/*
    id: end-of-file-fixer
  - id: debug-statements
  - id: check-case-conflict
  - id: check-json
  - args:
    - --unsafe
    id: check-yaml
  - id: mixed-line-ending
  - id: check-toml
  - id: pretty-format-json
  - id: check-docstring-first
  - id: check-symlinks
  - id: detect-private-key
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --skip=B101
    id: bandit
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
- hooks:
  - additional_dependencies:
    - radon
    args:
    - cc
    - --min=C
    - --total-average
    - --exclude=tests/*.py
    entry: radon
    id: radon
    language: python
    name: radon
    verbose: true
  repo: local
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.21.3
