[tool.poetry]
name = "fetchi"
version = "0.1.0"
description = "HTTP Backend to Fetch Data"
authors = ["Shiny Brar <charanjotbrar@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sanic = {version = "^23.12.1", extras = ["ext"]}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
