name: Continous Integration

# Run on push or PR to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    -
      # Install the extra dev dependencies
      name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev
    -
      name: Run tests
      run: poetry run pytest -v
