name: Continous Integration

# Run on push or PR to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
        name: Install dependencies
        run: pip install .
    -
        name: Run tests
        run: pytest -v
